### PR TITLE
Implement parallel jobs

### PR DESCRIPTION
**Pull request by brstgt**
Currently all jobs are processed sequentially. With async IO this is not needed.

### CODE REVIEW

**Comment by bzikarsky** [comment]
I like this! :-) Are you open to add some tests to the Worker functionality? The class is not tested at all at the moment. :-|

**Comment by brstgt** [comment]
Hmmm. I have a system test inhouse with a real gearman. Writing a unit test
for this case is will be quite complex

2017-09-20 9:34 GMT+02:00 Benjamin Zikarsky <notifications@github.com>:

**Comment by bzikarsky** [comment]
Let's keep it at that then. If you feel like adding more tests to this library, I'll happily merge a integration test harness or a foundation for such a test suite. :wink:

**Comment by brstgt** [comment]
Du you have an idea if it is possible to run a gearman-server in travis?

**Comment by bzikarsky** [comment]
Shouldn't be a problem really. You can install whatever software you like in the travis containers. `sudo apt-get install gearman-job-server` should do the trick.

**Pull request merged**
